/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Methods.Method;
/**
 *
 * @author Triton
 */
public class frmDescripcionFuncion extends javax.swing.JInternalFrame {
    private Integer _intID;
    private Method _metTypeMethod;
    MDI frmParent;
    /**
     * Creates new form frmDescripcionFuncion
     */
    public frmDescripcionFuncion() {
        initComponents();
    }
    
    public frmDescripcionFuncion(MDI frmParent, int intID, Method metTypeMethod) {
        this._intID = intID;
        this.frmParent = frmParent;
        this._metTypeMethod = metTypeMethod;
        initComponents();
        this.display();
    }
    
    private void display(){
        String strDescription = "";        
        strDescription += (this._metTypeMethod.getName() != null && !this._metTypeMethod.getName().isEmpty() ? "Nombre: " + this._metTypeMethod.getName() + "\n" : "");
        strDescription += (this._metTypeMethod.getType() != null && !this._metTypeMethod.getType().isEmpty() ? "Tipo: " + this._metTypeMethod.getType() + "\n" : "");
        
        this.pnlDescripcion.setText(strDescription.toUpperCase());
    }
               

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlDescripcion = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("EGA - Descripción");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ICON.png"))); // NOI18N

        pnlDescripcion.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        pnlDescripcion.setText("NOMBRE: Ranking\nTIPO: Operador de Selecion.\n\nDescripción: este operador sirve para algo...bla bla blas\n\n\nParámetros: el parametro CANTIDAD especifica cuántos individuos seleccionará el método.");
        pnlDescripcion.setEnabled(false);
        pnlDescripcion.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jScrollPane1.setViewportView(pnlDescripcion);

        jButton1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButton1.setText("Cerrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(296, 296, 296))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane pnlDescripcion;
    // End of variables declaration//GEN-END:variables
}
