/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


package Formularios;

import helpers.*;
import java.util.ArrayList;
import Clase.Principal.EGA;
import configuration.*;
import java.io.IOException;
import java.io.File;
import java.awt.Desktop;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
/**
 *
 * @author Triton
 */
public class MDI extends javax.swing.JFrame {
    private ArrayList<String> _arrFrm = new ArrayList<String>();
    file_handler fh = new file_handler();
    Paths paths = new Paths();
    
    /**
     * Creates new form MDI
     */
    public MDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        fcOpenSolution = new javax.swing.JFileChooser();
        Contenedor = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuAbrirSolucion = new javax.swing.JMenuItem();
        mnuCrearSolucion = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuEditarCromosoma = new javax.swing.JMenuItem();
        mnuEditarAptitud = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuEditarOeradorSeleccion = new javax.swing.JMenuItem();
        mnuEditarOperadorCruzamiento = new javax.swing.JMenuItem();
        mnuEditarOperadorMutacion = new javax.swing.JMenuItem();
        mnuEditarOperadorParada = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuAbrirRecursos = new javax.swing.JMenuItem();
        mnuCerrarAplicacion = new javax.swing.JMenu();
        mnuAyudaAbrir = new javax.swing.JMenuItem();
        mnuAyudaAcercaDe = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EGA");
        setPreferredSize(new java.awt.Dimension(1025, 720));

        Contenedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Contenedor.setPreferredSize(new java.awt.Dimension(1020, 680));

        jMenu1.setText("Solución");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        mnuAbrirSolucion.setText("Abrir");
        mnuAbrirSolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAbrirSolucionActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAbrirSolucion);

        mnuCrearSolucion.setText("Crear");
        mnuCrearSolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCrearSolucionActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCrearSolucion);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Editar");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        mnuEditarCromosoma.setText("Cromosoma");
        mnuEditarCromosoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditarCromosomaActionPerformed(evt);
            }
        });
        mnuEditarCromosoma.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                mnuEditarCromosomaMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenu4.add(mnuEditarCromosoma);

        mnuEditarAptitud.setText("Función de Aptitud");
        mnuEditarAptitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditarAptitudActionPerformed(evt);
            }
        });
        jMenu4.add(mnuEditarAptitud);

        jMenu3.setText("Operador");

        mnuEditarOeradorSeleccion.setText("Selección");
        mnuEditarOeradorSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditarOeradorSeleccionActionPerformed(evt);
            }
        });
        jMenu3.add(mnuEditarOeradorSeleccion);

        mnuEditarOperadorCruzamiento.setText("Cruzamiento");
        mnuEditarOperadorCruzamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditarOperadorCruzamientoActionPerformed(evt);
            }
        });
        jMenu3.add(mnuEditarOperadorCruzamiento);

        mnuEditarOperadorMutacion.setText("Mutación");
        mnuEditarOperadorMutacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditarOperadorMutacionActionPerformed(evt);
            }
        });
        jMenu3.add(mnuEditarOperadorMutacion);

        mnuEditarOperadorParada.setText("Parada");
        mnuEditarOperadorParada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditarOperadorParadaActionPerformed(evt);
            }
        });
        jMenu3.add(mnuEditarOperadorParada);

        jMenu4.add(jMenu3);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Recursos");

        mnuAbrirRecursos.setText("Abrir");
        mnuAbrirRecursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAbrirRecursosActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAbrirRecursos);

        jMenuBar1.add(jMenu2);

        mnuCerrarAplicacion.setText("Opciones");
        mnuCerrarAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCerrarAplicacionActionPerformed(evt);
            }
        });

        mnuAyudaAbrir.setText("Abrir Manual");
        mnuAyudaAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAyudaAbrirActionPerformed(evt);
            }
        });
        mnuCerrarAplicacion.add(mnuAyudaAbrir);

        mnuAyudaAcercaDe.setText("Acerca de");
        mnuAyudaAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAyudaAcercaDeActionPerformed(evt);
            }
        });
        mnuCerrarAplicacion.add(mnuAyudaAcercaDe);

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuCerrarAplicacion.add(mnuSalir);

        jMenuBar1.add(mnuCerrarAplicacion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String openSolution(String strFilePath){
        File file = new File(strFilePath);
        fcOpenSolution.setCurrentDirectory(file);
        String strPathFileToRead = ChooseFile();
        return strPathFileToRead;
    }
    
        public String ChooseFile(){
        int returnVal = fcOpenSolution.showOpenDialog(this);
        if (returnVal == 0) {
            File file = fcOpenSolution.getSelectedFile();
            try {
                return file.getAbsolutePath();
            } catch (Exception ex) {
                System.out.println("problem accessing file" + file.getAbsolutePath());
                return "";
            }
        }
        return "";
    }
    
    
    public void AbrirVentana (String strClase, boolean blnSelectFile){
        String strPathSolution = this.openSolution(paths.strSoluciones);
        javax.swing.JInternalFrame frm = new frmSolucion(this, strPathSolution);
        this.open(frm);
    }
    
    public void AbrirVentana ( String strClase )
    {

        javax.swing.JInternalFrame frm = new javax.swing.JInternalFrame();
        
        switch (strClase) 
        {
            case "frmSolucion":
        
              //  if (!this._arrFrm.contains(forms.Solucion)){
                frm = new frmSolucion(this);
              //      this._arrFrm.add(forms.Solucion);
              //  }
            break;

            case "frmEditor":
        
            frm = new frmEditor();
            break;

            case "frmRecursos":
            frm = new frmRecursos();
            break;
                
            case "frmDescripcionFuncion":
            frm = new frmDescripcionFuncion();
                
            break;
                
            case "frmGrafica":
            frm = new frmDescripcionFuncion();
            break;

            case "frmInformeConfiguracion":
            frm = new frmInformeConfiguracion();
            break;
                
            case "frmInforme":
            frm = new frmInforme();
            break;
                
            case "frmAcerca":
            frm = new frmAcerca();
            break;

            default:
            JOptionPane.showMessageDialog(this, "[Error MDI.AbrirVentana]: Especificación incorrecta de formulario.", "Error", 0);

        } //FIN SWITCH
   
        this.open(frm);
      
    }
    
    public void open(javax.swing.JInternalFrame frm){
        // agrego y muestro el form que se instanció.
        Contenedor.add(frm);

        //lo centro un poco
        frm.setLocation((Contenedor.getWidth() - frm.getWidth())/2,
        (Contenedor.getHeight()- frm.getHeight())/3);
        
        frm.show();
    }
    
    private void mnuAbrirSolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAbrirSolucionActionPerformed
        this.AbrirVentana("frmSolucion", true);
    }//GEN-LAST:event_mnuAbrirSolucionActionPerformed

    private void mnuCerrarAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCerrarAplicacionActionPerformed

        
        // [de DARIO]:
        // PONER ACA EL FUCKING CODIGO PARA QUE EL PROGRAMA SE CIERRE. System.exit(0) NO ME ANDA..
        // COMPROBAR CON ALGUNA VARIABLE DE ESTADO, SI HAY TRABAJO POR GUARDAR Y PREGUNTARLE AL USUARIO.
        // TODO add your handling code here:
        int rpta;                                          
        rpta=JOptionPane.showConfirmDialog(this, "Esta seguro de salir?","Salir", 0);
        if(rpta==0)
        {
            this.dispose();
        }
        
        
    }//GEN-LAST:event_mnuCerrarAplicacionActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed


    }//GEN-LAST:event_jMenu4ActionPerformed

    private void mnuEditarCromosomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditarCromosomaActionPerformed

        this.AbrirVentana("frmEditor");

    }//GEN-LAST:event_mnuEditarCromosomaActionPerformed

    private void mnuEditarAptitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditarAptitudActionPerformed

        this.AbrirVentana("frmEditor");
        
    }//GEN-LAST:event_mnuEditarAptitudActionPerformed

    private void mnuAyudaAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAyudaAcercaDeActionPerformed

        this.AbrirVentana("frmAcerca");        
    }//GEN-LAST:event_mnuAyudaAcercaDeActionPerformed

    private void mnuAyudaAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAyudaAbrirActionPerformed

        try 
        {
            File path = new File ("EGA.pdf");
            Desktop.getDesktop().open(path);
        }
        catch (IOException ex) 
        {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_mnuAyudaAbrirActionPerformed

    private void mnuAbrirRecursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAbrirRecursosActionPerformed

       
        this.AbrirVentana("frmRecursos");
        
    }//GEN-LAST:event_mnuAbrirRecursosActionPerformed

    private void mnuEditarCromosomaMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_mnuEditarCromosomaMenuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuEditarCromosomaMenuKeyPressed

    private void mnuEditarOeradorSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditarOeradorSeleccionActionPerformed
        
        this.AbrirVentana("frmEditor");                
        
    }//GEN-LAST:event_mnuEditarOeradorSeleccionActionPerformed

    private void mnuEditarOperadorCruzamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditarOperadorCruzamientoActionPerformed
        
        this.AbrirVentana("frmEditor");
        
    }//GEN-LAST:event_mnuEditarOperadorCruzamientoActionPerformed

    private void mnuEditarOperadorMutacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditarOperadorMutacionActionPerformed
        
        this.AbrirVentana("frmEditor");
        
    }//GEN-LAST:event_mnuEditarOperadorMutacionActionPerformed

    private void mnuEditarOperadorParadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditarOperadorParadaActionPerformed
        
        this.AbrirVentana("frmEditor");
        
    }//GEN-LAST:event_mnuEditarOperadorParadaActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed

        //ACA HABRIA QUE VERIFICAR EL ESTADO DE LAS VENTANAS, Y SI HAY ALGUNA
        //VARIABLE QUE INDICA QUE NO SE DEBERIA SALIR SIN CONFIRMAION, ENTONCES
        //AHI SI HACER LA PREGUNTA, DE LO CONTRARIO SALIR SIN PREGUNTAR. (DARIO)
        
        int rpta;                                          
        rpta=JOptionPane.showConfirmDialog(this, "¿Confirma cerrar la aplicación?","Salir del Sistema", 0);
        if(rpta==0)
            this.dispose();
        
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuCrearSolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCrearSolucionActionPerformed
        // TODO add your handling code here:
        this.AbrirVentana("frmSolucion");
    }//GEN-LAST:event_mnuCrearSolucionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Contenedor;
    private javax.swing.JFileChooser fcOpenSolution;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem mnuAbrirRecursos;
    private javax.swing.JMenuItem mnuAbrirSolucion;
    private javax.swing.JMenuItem mnuAyudaAbrir;
    private javax.swing.JMenuItem mnuAyudaAcercaDe;
    private javax.swing.JMenu mnuCerrarAplicacion;
    private javax.swing.JMenuItem mnuCrearSolucion;
    private javax.swing.JMenuItem mnuEditarAptitud;
    private javax.swing.JMenuItem mnuEditarCromosoma;
    private javax.swing.JMenuItem mnuEditarOeradorSeleccion;
    private javax.swing.JMenuItem mnuEditarOperadorCruzamiento;
    private javax.swing.JMenuItem mnuEditarOperadorMutacion;
    private javax.swing.JMenuItem mnuEditarOperadorParada;
    private javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables
}
