/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clase.Principal.ImagenFondo;
import Listeners.InternalFrameCloseListener;
import Methods.*;
import Solutions.Solution;
import configuration.*;
import enums.*;
import helpers.*;
import java.awt.Cursor;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Triton
 */
public class MDI extends javax.swing.JFrame {
    private ArrayList<Integer> _arrIDSolOpened = new ArrayList<Integer>();
    file_handler fh = new file_handler();
    Paths paths = new Paths();

    /**
     * Creates new form MDI
     */
    public MDI() {
        initComponents();
        Contenedor.setBorder(new ImagenFondo());

   //     InternalFrameCloseListener closeListener = new InternalFrameCloseListener();
   //     this.addInternalFrameListener (closeListener.getInternalFrameCloseListener());

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        fcOpenSolution = new javax.swing.JFileChooser();
        Contenedor = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuAbrirSolucion = new javax.swing.JMenuItem();
        mnuCrearSolucion = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuVerRecursos = new javax.swing.JMenuItem();
        mnuNuevoRecurso = new javax.swing.JMenu();
        mnuEditarCromosoma = new javax.swing.JMenuItem();
        mnuEditarAptitud = new javax.swing.JMenuItem();
        mnuEditarAyudante = new javax.swing.JMenuItem();
        mnuResultados = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuEditarOperadorSeleccion = new javax.swing.JMenuItem();
        mnuEditarOperadorCruzamiento = new javax.swing.JMenuItem();
        mnuEditarOperadorMutacion = new javax.swing.JMenuItem();
        mnuEditarOperadorParada = new javax.swing.JMenuItem();
        mnuAbrirSoluciones = new javax.swing.JMenuItem();
        mnuCerrarAplicacion = new javax.swing.JMenu();
        mnuAyudaAbrir = new javax.swing.JMenuItem();
        mnuAyudaAcercaDe = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("EGA");
        setPreferredSize(new java.awt.Dimension(1025, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Contenedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Contenedor.setPreferredSize(new java.awt.Dimension(1020, 680));

        jMenu1.setText("Solución");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        mnuAbrirSolucion.setText("Abrir");
        mnuAbrirSolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAbrirSolucionActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAbrirSolucion);

        mnuCrearSolucion.setText("Nueva");
        mnuCrearSolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCrearSolucionActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCrearSolucion);

        jMenuItem3.setText("Importar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Recursos");

        mnuVerRecursos.setText("Ver Recursos");
        mnuVerRecursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVerRecursosActionPerformed(evt);
            }
        });
        jMenu2.add(mnuVerRecursos);

        mnuNuevoRecurso.setText("Nuevo");
        mnuNuevoRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevoRecursoActionPerformed(evt);
            }
        });

        mnuEditarCromosoma.setText("Cromosoma");
        mnuEditarCromosoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditarCromosomaActionPerformed(evt);
            }
        });
        mnuEditarCromosoma.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                mnuEditarCromosomaMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        mnuNuevoRecurso.add(mnuEditarCromosoma);

        mnuEditarAptitud.setText("Función de Aptitud");
        mnuEditarAptitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditarAptitudActionPerformed(evt);
            }
        });
        mnuNuevoRecurso.add(mnuEditarAptitud);

        mnuEditarAyudante.setText("Carga de Datos");
        mnuEditarAyudante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditarAyudanteActionPerformed(evt);
            }
        });
        mnuNuevoRecurso.add(mnuEditarAyudante);

        mnuResultados.setText("Formato de Resultados");
        mnuResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuResultadosActionPerformed(evt);
            }
        });
        mnuNuevoRecurso.add(mnuResultados);

        jMenu3.setText("Operador");

        mnuEditarOperadorSeleccion.setText("Selección");
        mnuEditarOperadorSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditarOperadorSeleccionActionPerformed(evt);
            }
        });
        jMenu3.add(mnuEditarOperadorSeleccion);

        mnuEditarOperadorCruzamiento.setText("Cruzamiento");
        mnuEditarOperadorCruzamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditarOperadorCruzamientoActionPerformed(evt);
            }
        });
        jMenu3.add(mnuEditarOperadorCruzamiento);

        mnuEditarOperadorMutacion.setText("Mutación");
        mnuEditarOperadorMutacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditarOperadorMutacionActionPerformed(evt);
            }
        });
        jMenu3.add(mnuEditarOperadorMutacion);

        mnuEditarOperadorParada.setText("Parada");
        mnuEditarOperadorParada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditarOperadorParadaActionPerformed(evt);
            }
        });
        jMenu3.add(mnuEditarOperadorParada);

        mnuNuevoRecurso.add(jMenu3);

        jMenu2.add(mnuNuevoRecurso);

        mnuAbrirSoluciones.setText("Ver Soluciones");
        mnuAbrirSoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAbrirSolucionesActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAbrirSoluciones);

        jMenuBar1.add(jMenu2);

        mnuCerrarAplicacion.setText("Opciones");
        mnuCerrarAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCerrarAplicacionActionPerformed(evt);
            }
        });

        mnuAyudaAbrir.setText("Abrir Manual");
        mnuAyudaAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAyudaAbrirActionPerformed(evt);
            }
        });
        mnuCerrarAplicacion.add(mnuAyudaAbrir);

        mnuAyudaAcercaDe.setText("Acerca de");
        mnuAyudaAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAyudaAcercaDeActionPerformed(evt);
            }
        });
        mnuCerrarAplicacion.add(mnuAyudaAcercaDe);

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuCerrarAplicacion.add(mnuSalir);

        jMenuBar1.add(mnuCerrarAplicacion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Integer generateNewSolutionID() {
        if (this._arrIDSolOpened.isEmpty() == true) {
            this._arrIDSolOpened.add(1);
            return 1;
        }

        Integer lastID = this._arrIDSolOpened.get(this._arrIDSolOpened.size() - 1);
        this._arrIDSolOpened.add(lastID + 1);
        return lastID + 1;
    }

    private String openSolution(String strFilePath) {
        File file = new File(strFilePath);
        fcOpenSolution.setCurrentDirectory(file);
        return ChooseFile();
    }

    public String ChooseFile() {
        int returnVal = fcOpenSolution.showOpenDialog(this);
        if (returnVal == 0) {
            File file = fcOpenSolution.getSelectedFile();
            try {
                return file.getAbsolutePath();
            } catch (NullPointerException ex) {
            } catch (Exception ex) {
                System.out.println("problem accessing file" + file.getAbsolutePath());
                return "";
            }
        }
        return "";
    }

    public void UpdateResourcesTables() {
        for (javax.swing.JInternalFrame frm : Contenedor.getAllFrames()) {
            String frmClass = frm.getClass().toString().split("class Formularios.")[1];
            if (frmClass.equals(forms.Recursos)) {
                ((frmRecursos) frm).ReloadResourcesTable();
            }
        }
    }

    public javax.swing.JInternalFrame AbrirVentana(String strClase, boolean blnSelectFile, boolean blnImport) {
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        String strPathSolution = this.openSolution(paths.strSoluciones);
        if (!strPathSolution.isEmpty()) {
            return this.OpenSpecificSolution(strPathSolution, blnImport);
        }
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        return new javax.swing.JInternalFrame();
    }

    public javax.swing.JInternalFrame OpenSpecificSolution(String strPathSolution, boolean blnImport){
        javax.swing.JInternalFrame frm = new javax.swing.JInternalFrame();
        frm = new frmSolucion(this, this.generateNewSolutionID(), strPathSolution, blnImport);

        javax.swing.JInternalFrame frame = this.open(frm);
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        return frame;
    }
    
    public javax.swing.JInternalFrame AbrirVentana(String strClase, Integer intID, Method strMethod, boolean canSaveAs) {
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        
        javax.swing.JInternalFrame frm = new javax.swing.JInternalFrame();

        switch (strClase) {
            case "frmEditor":
                frm = new frmEditor(this, intID, strMethod, canSaveAs);
                break;
            case "frmDescripcionFuncion":
                frm = new frmDescripcionFuncion(this, intID, strMethod);
                break;
        }
        javax.swing.JInternalFrame frame = this.open(frm);
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));        
        return frame;
    }

    public javax.swing.JInternalFrame AbrirRecursos(int intOperatorType) {
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        
        javax.swing.JInternalFrame frm = new frmRecursos(this, this.generateNewSolutionID(), intOperatorType);
        javax.swing.JInternalFrame frame = this.open(frm);
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        return frame;
    }

    public javax.swing.JInternalFrame AbrirVentana(String strClase) {
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        
        javax.swing.JInternalFrame frm = new javax.swing.JInternalFrame();

        switch (strClase) {
            case "frmSolucion":
                frm = new frmSolucion(this, this.generateNewSolutionID());
                break;
            case "frmEditor":
                frm = new frmEditor();
                break;
            case "frmRecursos":
                frm = new frmRecursos(this, this.generateNewSolutionID(), OperatorType.Method);
                break;
            case "frmDescripcionFuncion":
                frm = new frmDescripcionFuncion();
                break;
            case "frmGrafica":
                frm = new frmGrafica();
                break;
            case "frmInformeConfiguracion":
                frm = new frmInformeConfiguracion();
                break;
            case "frmInforme":
                frm = new frmInforme();
                break;
            case "frmAcerca":
                frm = new frmAcerca();
                break;
            default:
                JOptionPane.showMessageDialog(this, "[Error MDI.AbrirVentana]: Especificación incorrecta de formulario.", "Error", 0);
        }
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        return this.open(frm);
    }

    public javax.swing.JInternalFrame open(javax.swing.JInternalFrame frm) {
        Contenedor.add(frm);

        frm.setLocation((Contenedor.getWidth() - frm.getWidth()) / 2, (Contenedor.getHeight() - frm.getHeight()) / 2);

        frm.setVisible(true);
        frm.toFront();
        return frm;
    }

    private void mnuAbrirSolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAbrirSolucionActionPerformed
        this.AbrirVentana("frmSolucion", true, false);
    }//GEN-LAST:event_mnuAbrirSolucionActionPerformed

    private void mnuCerrarAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCerrarAplicacionActionPerformed
        int rpta;
        rpta = JOptionPane.showConfirmDialog(this, "Esta seguro de salir?", "Salir", 0);
        if (rpta == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_mnuCerrarAplicacionActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void mnuNuevoRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevoRecursoActionPerformed
    }//GEN-LAST:event_mnuNuevoRecursoActionPerformed

    private void mnuEditarCromosomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditarCromosomaActionPerformed
        Method met = new Method();
        met.setType("CROMOSOMA");
        this.AbrirVentana("frmEditor", this.generateNewSolutionID(), met, true);
    }//GEN-LAST:event_mnuEditarCromosomaActionPerformed

    private void mnuEditarAptitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditarAptitudActionPerformed
        Method met = new Method();
        met.setType("FUNCIÓN APTITUD");
        this.AbrirVentana("frmEditor", this.generateNewSolutionID(), met, true);
    }//GEN-LAST:event_mnuEditarAptitudActionPerformed

    private void mnuAyudaAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAyudaAcercaDeActionPerformed

        this.AbrirVentana("frmAcerca");
    }//GEN-LAST:event_mnuAyudaAcercaDeActionPerformed

    private void mnuAyudaAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAyudaAbrirActionPerformed

        try {
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            File path = new File("C:\\EGA\\system\\help\\EGA.pdf");
            Desktop.getDesktop().open(path);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

    }//GEN-LAST:event_mnuAyudaAbrirActionPerformed

    private void mnuVerRecursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVerRecursosActionPerformed
        this.openResource(OperatorType.Method);
    }//GEN-LAST:event_mnuVerRecursosActionPerformed

    private void mnuEditarCromosomaMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_mnuEditarCromosomaMenuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuEditarCromosomaMenuKeyPressed

    private void mnuEditarOperadorSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditarOperadorSeleccionActionPerformed
        Method met = new Method();
        met.setType("SELECCIÓN");
        this.AbrirVentana("frmEditor", this.generateNewSolutionID(), met, true);
    }//GEN-LAST:event_mnuEditarOperadorSeleccionActionPerformed

    private void mnuEditarOperadorCruzamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditarOperadorCruzamientoActionPerformed
        Method met = new Method();
        met.setType("CRUZAMIENTO");
        this.AbrirVentana("frmEditor", this.generateNewSolutionID(), met, true);

    }//GEN-LAST:event_mnuEditarOperadorCruzamientoActionPerformed

    private void mnuEditarOperadorMutacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditarOperadorMutacionActionPerformed
        Method met = new Method();
        met.setType("MUTACIÓN");
        this.AbrirVentana("frmEditor", this.generateNewSolutionID(), met, true);
    }//GEN-LAST:event_mnuEditarOperadorMutacionActionPerformed

    private void mnuEditarOperadorParadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditarOperadorParadaActionPerformed
        Method met = new Method();
        met.setType("PARO");
        this.AbrirVentana("frmEditor", this.generateNewSolutionID(), met, true);
    }//GEN-LAST:event_mnuEditarOperadorParadaActionPerformed

    public javax.swing.JInternalFrame GetWindowsEditing(Method met) {
        for (javax.swing.JInternalFrame frm : Contenedor.getAllFrames()) {
            if ((frm.getClass().toString().split("class Formularios.")[1]).equals(forms.Editor)) {
                if (((frmEditor)frm).isEditing(met)) {
                    return frm;
                }
            }
        }
        return null;
    }
    
    public javax.swing.JInternalFrame GetWindowsEditing(Solution sol) {
        for (javax.swing.JInternalFrame frm : Contenedor.getAllFrames()) {
            if (frm.isVisible()){
                if ((frm.getClass().toString().split("class Formularios.")[1]).equals(forms.Solucion)) {
                    if (((frmSolucion)frm).isEditing(sol)){
                        return frm;
                    }
                }
            }
        }
        return null;
    }

    public void setWindowsToFront(javax.swing.JInternalFrame frm) {
        frm.toFront();
    }

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        this.formWindowClosing(null);
        if (this.getDefaultCloseOperation() == EXIT_ON_CLOSE)
            this.dispose();
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuCrearSolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCrearSolucionActionPerformed
        // TODO add your handling code here:
        this.AbrirVentana("frmSolucion");
    }//GEN-LAST:event_mnuCrearSolucionActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.AbrirVentana("frmSolucion", true, true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mnuEditarAyudanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditarAyudanteActionPerformed
        // TODO add your handling code here:        
        Method met = new Method();
        met.setType("AYUDANTE");
        this.AbrirVentana("frmEditor", this.generateNewSolutionID(), met, true);
    }//GEN-LAST:event_mnuEditarAyudanteActionPerformed

    private void mnuResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuResultadosActionPerformed
        // TODO add your handling code here:
        Method met = new Method();
        met.setType("INFORME");
        this.AbrirVentana("frmEditor", this.generateNewSolutionID(), met, true);
    }//GEN-LAST:event_mnuResultadosActionPerformed

    private void mnuAbrirSolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAbrirSolucionesActionPerformed
        // TODO add your handling code here:
        this.openResource(OperatorType.Solution);
    }//GEN-LAST:event_mnuAbrirSolucionesActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        for (javax.swing.JInternalFrame frm : Contenedor.getAllFrames()) {
            String frmClass = frm.getClass().toString().split("class Formularios.")[1];
            if (frmClass.equals(forms.Recursos))
                ((frmRecursos) frm).CloseAll();
            else if (frmClass.equals(forms.Editor))
                ((frmEditor) frm).CloseMe();
            else if(frmClass.equals(forms.Solucion))
                ((frmSolucion) frm).CloseAll();
            else
                frm = null;
        }
        
        if (Contenedor.getAllFrames().length == 0){
            this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void openResource(int intType) {
        this.AbrirRecursos(intType);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Contenedor;
    private javax.swing.JFileChooser fcOpenSolution;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem mnuAbrirSolucion;
    private javax.swing.JMenuItem mnuAbrirSoluciones;
    private javax.swing.JMenuItem mnuAyudaAbrir;
    private javax.swing.JMenuItem mnuAyudaAcercaDe;
    private javax.swing.JMenu mnuCerrarAplicacion;
    private javax.swing.JMenuItem mnuCrearSolucion;
    private javax.swing.JMenuItem mnuEditarAptitud;
    private javax.swing.JMenuItem mnuEditarAyudante;
    private javax.swing.JMenuItem mnuEditarCromosoma;
    private javax.swing.JMenuItem mnuEditarOperadorCruzamiento;
    private javax.swing.JMenuItem mnuEditarOperadorMutacion;
    private javax.swing.JMenuItem mnuEditarOperadorParada;
    private javax.swing.JMenuItem mnuEditarOperadorSeleccion;
    private javax.swing.JMenu mnuNuevoRecurso;
    private javax.swing.JMenuItem mnuResultados;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenuItem mnuVerRecursos;
    // End of variables declaration//GEN-END:variables
}
