/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;
import configuration.Paths;
import javax.swing.JLabel;

/**
 *
 * @author Nicolas
 */
public class frmSplash extends javax.swing.JFrame {
    public Paths paths = new Paths();
    /**
     * Creates new form frmSplash
     */
    public frmSplash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblDerechos = new javax.swing.JLabel();
        lblVersion = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblSplash = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setMinimumSize(new java.awt.Dimension(530, 300));
        setName("frmSplash"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(520, 200));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("SansSerif", 3, 23)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Easy Genetic Algorithms");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 350, 54));

        lblDerechos.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        lblDerechos.setForeground(new java.awt.Color(255, 255, 255));
        lblDerechos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDerechos.setText("Copyright © 2012 - EGA");
        getContentPane().add(lblDerechos, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 276, 294, 20));

        lblVersion.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblVersion.setForeground(new java.awt.Color(255, 255, 255));
        lblVersion.setText("1.0");
        getContentPane().add(lblVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 40, 30));

        lblEstado.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(255, 255, 255));
        lblEstado.setText("Cargando");
        getContentPane().add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 148, 30));

        lblSplash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/res/adn_splash.png"))); // NOI18N
        lblSplash.setText("jLabel1");
        getContentPane().add(lblSplash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 532, 302));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 220, 118, 26));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSplash().setVisible(true);
            }
        });
    }
    public JLabel Estado () {return lblEstado;}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDerechos;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSplash;
    private javax.swing.JLabel lblVersion;
    // End of variables declaration//GEN-END:variables
}
